// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifzbcfopboceogkwhukv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmemJjZm9wYm9jZW9na3dodWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjMyOTIsImV4cCI6MjA2NTUzOTI5Mn0.a05rCurKQybPo-4mQv72ddYnypshSAdpgf9IJedFjn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);